# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets: # Contient la liste des filtres
        sidebar:
            quality: 75
            filters:
                thumbnail:
                    size: [80, 80]
                    mode: outbound
        pano:
            quality: 85
            filters:
                thumbnail:
                    size: [450,450]
                    mode: outbound
