twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        #locales: '%app.locales%'
        site_name: 'citizenz.info'
        site_name_full: 'Citizenz.info'
        site_slogan: 'Citizenz.info : blog geek & libre'
        site_url: 'citizenz.info'
        site_url_full: 'https://www.citizenz.info'
        site_mail: 'contact@citizenz.info'
        site_author: 'citizenz7'
        site_version: '2.1.1'
        site_year: '2021'
        site_keywords: 'blog, citizenz, net, web, sql, php, html, linux, debian, ubuntu, html, css, symfony, laravel, angular, développement, réseau, système, os, exploitation, rss, news, infos, articles, posts, serveur, VPS, dédié, android, libre, windows, sécurité, terminal, console, letsencrypt, HTTPS, phpmyadmin, hébergement, files, nginx, apache, git, github, javascript, jquery, mail, postfix, dovecot, rspamd, rainloop, dkim, spf, dmark, seedbox, rtorrent, rutorrent, ssh, scp, arch, manjaro, xfce, webdav, certbot, mariadb, rsync, sudo'
        site_presentation: 'Blog d''un geek quinqua nivernais fan d''ovalie, de linuxerie, de musique et de Net'
        site_kaamelott1: 'Le code c''est "le code" ? Ça va, ils se sont pas trop cassé le bonnet, pour l''trouver celui-là ! (Kaamelott, Livre III, Poltergeist)'
        github_repo: 'https://github.com/citizenz7/blog'
        github_url: 'https://github.com/citizenz7'
        twitter_url: 'https://twitter.com/citizenz58'
        facebook_url: 'https://www.facebook.com/o.prieur58/'
        linkedin_url: 'https://www.linkedin.com/in/olivier-prieur/'
        discord_url: 'https://discord.gg/neVZtE3'

when@test:
    twig:
        strict_variables: true
